clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 5 # default: 10

    # The number of clients selected in each round
    per_round: 5 # default: 10

    # Should the clients compute test accuracy locally?
    do_test: true

    # Whether or not to simulate communication when running on a single machine
    comm_simulation: true
    compute_comm_time: true

    # Whether client heterogeneity should be simulated
    speed_simulation: true

    # The simulation distribution
    simulation_distribution:
        #staleness is simulated from uniform distribution as mentioned in Section 5.2
        distribution: uniform
        low: 0
        high: 10

    additional_delay:
        low: 0
        high: 5

    random_seed: 42

server:
    address: 127.0.0.1
    port: 8998
    synchronous: false
    simulate_wall_time: false
    do_test: false
    do_final_test: true

    # Parameter for FedAsync
    periodic_interval: 10
    staleness_bound: 99999
    minimum_clients_aggregated: 1
    mixing_hyperparameter: 0.9
    adaptive_mixing: true
    staleness_weighting_function:
        type: polynomial
        a: 10

    checkpoint_path: models/fedasync/cifar10
    model_path: models/fedasync/cifar10

    downlink_bandwidth: 100
    uplink_bandwidth: 100

    random_seed: 42

data:
    # The training and testing dataset
    datasource: CIFAR10 # Default: PartitionedCIFAR10

    # IID or non-IID?
    sampler: all_inclusive
    testset_sampler: all_inclusive

    random_seed: 42
    reload_data: true

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 10

    # The maximum number of clients running concurrently
    max_concurrency: 10

    # The machine learning model
    model_name: lowgpuCifar10

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 64
    optimizer: RMSprop

    loss_criterion: CrossEntropyLoss

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    experiment_name: "cifar10_high-poly"
    optimizer:
        lr: 0.001
        momentum: 0.0 # learning rate is fixed as in Appendix C.2
        weight_decay: 0

results:
    result_path: results/fedasync/cifar10
    # Write the following parameter(s) into a CSV
    types: round, elapsed_time, comm_time, round_time, comm_overhead, train_loss, test_loss, auroc, accuracy, precision, recall
